# Generated by Django 3.2 on 2022-06-30 23:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountconfirmation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
