# Generated by Django 3.2 on 2022-07-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accountconfirmation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accept_terms_and_conditions',
            field=models.BooleanField(default=False),
        ),
    ]
